sudo: required

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  #- >
  #  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  #  | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  #- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

  # clone apiv3 for e2e testing
  - git clone https://github.com/cualbondi/apiv3.git --depth 1

  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose-travis.yml up -d
  - docker-compose -f docker-compose-travis.yml exec apiv3 python manage.py migrate
  - docker-compose -f docker-compose-travis.yml exec apiv3 python manage.py loaddata lineas.json recorridos.json provincias.json ciudades.json calles.json zonas.json pois.json
  - docker-compose -f docker-compose-travis.yml ps

script:
  - docker-compose -f docker-compose-travis.yml exec web-buscador bash -c "yarn && yarn lint"
  - docker-compose -f docker-compose-travis.yml exec web-buscador bash -c "yarn && yarn test:e2e"
