version: '3.2'

services:

    web-buscador:
        image: cypress/base:10
        ports:
            - 8083:8080
        command: bash -c "yarn && yarn serve"
        working_dir: /src
        volumes:
            - ./web-buscador:/src

    apiv3:
        build:
          context: https://github.com/cualbondi/apiv3.git
          dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        env_file: .env.local.travis
        volumes:
            - .:/app
        command: /start.sh

    db:
        image: cualbondi/postgres
        env_file: .env.local.travis

    cache:
        image: memcached:alpine
