version: '3.2'

services:
  web-buscador:
    image: cualbondi/web-buscador
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-8080}:8080'
    volumes:
      - ./src/:/app/src
      - ./public/:/app/public
      # Excludes node_modules from mounting
      # - /var/www/node_modules
    stdin_open: true
    tty: true
