version: '3.2'

services:

    web-buscador:
        image: cypress/base:8
        depends_on:
          - web
        env_file: .env.local.travis
        ports:
            - 8083:8080
        command: tail -f /dev/null
        working_dir: /src
        volumes:
            - .:/src

    web:
        build:
            context: ./web
            dockerfile: docker/local/Dockerfile
        depends_on:
            - db
            - cache
        env_file: .env.local.travis
        volumes:
            - ./web:/app:cached
        ports:
            - 8082:8000
        command: ["/start.sh"]

    db:
        image: cualbondi/postgres
        env_file: .env.local.travis

    cache:
        image: memcached:alpine
